{{- $envAll := . }}

# Add endpoint URI lookup for RetailStore Postgresql DB Connection
{{- if empty .Values.conf.rstore.database.database_connect_string -}}
{{- tuple "postgresql" "internal" "user" "postgresql" . | include "helm-toolkit.endpoints.authenticated_endpoint_uri_lookup" | set .Values.conf.rstore.database "database_connect_string" | quote | trunc 0 -}}
{{- end -}}

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: rstore-etc
data:
  retailstore.conf: |+
{{ include "helm-toolkit.utils.to_oslo_conf" .Values.conf.rstore | indent 4 }}
  retailstore-paste.ini: |+
{{ include "helm-toolkit.utils.to_ini" .Values.conf.paste | indent 4 }}
