{{- if .Values.manifests.service }}
{{- $envAll := . }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ tuple "rstore" "internal" . | include "helm-toolkit.endpoints.hostname_short_endpoint_lookup" }}
spec:
  ports:
    {{ if .Values.network.enable_node_port }}
    - name: http
      nodePort: {{ .Values.network.node_port }}
      port: {{ .Values.network.port }}
      protocol: TCP
      targetPort: {{ .Values.network.port }}
    {{ else }}
    - name: http
      port: {{ .Values.network.port }}
      protocol: TCP
      targetPort: {{ .Values.network.port }}
    {{ end }}
  selector:
{{ tuple $envAll "rstore-api" "server" | include "helm-toolkit.snippets.kubernetes_metadata_labels" | indent 4 }}
  {{ if .Values.network.enable_node_port }}
  type: NodePort
  {{ end }}
{{- end }}
