# Default values for rstore.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

labels:
  node_selector_key: rstore
  node_selector_value: enabled

replicaCount: 1

images:
  tags:
    dep_check: quay.io/stackanetes/kubernetes-entrypoint:v0.3.0
    db_init: docker.io/postgres:9.5
    db_sync: quay.io/code_r/rstore:latest

image:
  repository: nginx
  tag: stable
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: false
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  path: /
  hosts:
    - chart-example.local
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #  cpu: 100m
  #  memory: 128Mi
  # requests:
  #  cpu: 100m
  #  memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}

conf:
  paste:
    filter:auth:
      paste.filter_factory: retailstore.util:auth_filter_factory
    app:store-api:
      paste.app_factory: retailstore.server:api_app_factory
    pipeline:main:
      pipeline: auth store-api
  rstore:
    DEFAULT:
      bind_host: 0.0.0.0
      bind_port: 9000
      some_default_option: 20
      api_paste_config: retailstore-paste.ini
    database:
      database_connect_string: postgresql://postgres:password@192.168.99.100:31000/retail_store

dependencies:
  db_init:
    services:
    - service: postgresql
      endpoint: internal
  db_sync:
    jobs:
    - rstore-db-init
    services:
    - service: postgresql
      endpoint: internal

manifests:
  job_db_init: true
  secret_db: true
  job_db_sync: true
  configmap_bin: true
  configmap_etc: true
  deployment: true
  service: true

pod:
  mounts:

    rstore_db_init:
      init_container: null
      rstore_db_init:
  resources:
    enabled: false
    api:
      limits:
        memory: "128Mi"
        cpu: "100m"
      requests:
        memory: "128Mi"
        cpu: "100m"
    jobs:
      db_init:
        limits:
          memory: "128Mi"
          cpu: "100m"
        requests:
          memory: "128Mi"
          cpu: "100m"
      db_sync:
        limits:
          memory: "128Mi"
          cpu: "100m"
        requests:
          memory: "128Mi"
          cpu: "100m"

secrets:
  postgresql:
    admin: rstore-db-admin
    user: rstore-db-user

endpoints:
  cluster_domain_suffix: cluster.local
  rstore:
    name: rstore
    hosts:
      default: rstore-int
      public: rstore-api
    port:
      api:
        default: 9000
        public: 80
    path:
      default: /api/v1.0
    scheme:
      default: http
    host_fqdn_override:
      default: null
  postgresql:
    name: postgresql
    auth:
      admin:
        username: postgres
        password: password
      user:
        username: postgres
        password: password
        database: rstore
    hosts:
      default: postgresql
    path: /rstore
    scheme: postgresql+psycopg2
    port:
      postgresql:
        default: 5432
    host_fqdn_override:
      default: null
